# Turn off permissions by setting this value to false
# By turning off permissions, everybody will have access to Gates
permissions: true # (DEFAULT: true)

# The default gate type, this will be applied to new Gates
default-type: default # (DEFAULT: default)

# The number of blocks to search for gate blocks in every direction from the gate sign
search-radius: 4 # (DEFAULT: 4)

# The maximum width and height of gates (Gate blocks)
maximum-size: 16 # (DEFAULT: 16)

# If gates should be allowed to branch out in different directions
branches: false # (DEFAULT: false)

# If debug messages should be displayed
debug: false # (DEFAULT: false)

# If actions should be stored in the console log (Live in the console)
console-log: false # (DEFAULT: false)

# Gate types, these can be applied to gates for additional customization
type:
    default:
        delay: 16
        redstone: REDSTONE_OFF
    instant:
        delay: 0
        redstone: REDSTONE_OFF
    redstone:
        delay: 8
        redstone: REDSTONE_ON
    toggle:
        delay: 8
        redstone: REDSTONE_TOGGLE
