name: Gates
main: com.geekzmultimedia.gates.Gates
author: Tyrotoxism ,HiddenOwner, Geekz Multimedia
website: www.geekzmultimedia.com
version: 2.1beta
description: Gates for your Bukkit server
commands:
    gates:
        description: Used to modify gate signs to your liking
        usage: |
            /gates owner <player>
            /gates type <type>
            /gates redstone <ON|OFF|TOGGLE> 
       